resources:
  - namespace-wordpress.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml
  - mysql-service.yaml
  - mysql-endpoints.yaml
  - ingress.yaml

images:
  - name: wordpress-app
    newName: 753675398055.dkr.ecr.us-east-1.amazonaws.com/amir-wordpress-app
    newTag: "initial"
